name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  push_to_registry:
    name: Build Docker Image and push to Docker Hub
    runs-on: ubuntu-latest 
    strategy:
      matrix:
       include:
         - dockerfile: ./user-sync/Dockerfile
           tags: "damnwar/cyclos-docker_user-sync:latest"
         - dockerfile: ./ad-notification/Dockerfile
           tags: "damnwar/cyclos-docker_ad-notification:latest"
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.tags }} 
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}            
